.TH DECEPTOR 1 "November 2025" "Deceptor Toolkit" "User Commands"
.SH NAME
deceptor \- Real-Time Network Deception & Packet Forgery Engine
.SH SYNOPSIS
.B deceptor
<interface> <target-ip>
.SH DESCRIPTION
Deceptor is a libpcap-based packet forgery engine used to create fake
network responses, deceive scanners, and generate artificial open ports.
.SH OPTIONS
None.
.SH EXAMPLES
sudo deceptor eth0 192.168.1.10
.SH AUTHOR
Created by MADJACK.
.SH LICENSE
MIT License.
